# Traefik static configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:  {}

api:
  # Dashboard at https://traefik.<domain>/dashboard/  (protected by basic-auth label)
  dashboard: true
  insecure: false

# Service discovery: read labels from Docker containers.
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: travel_net    # explicit network to avoid ambiguity
  file:
    filename: /etc/traefik/traefik_dynamic.yml # Point to the file above
    watch: true

# Two ACME resolvers: one for staging, one for production
certificatesResolvers:
  letsencrypt-staging:
    acme:
      email: "${ACME_EMAIL}"
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# docker-compose logs traefik
log:
  level: INFO

accessLog: {}
