-- Seed data — runs after 01-schema.sql on first container init./

INSERT INTO activity_types (name) VALUES
    ('beach'), ('hiking'), ('skiing'), ('city_break'),
    ('diving'), ('cultural'), ('wellness'), ('safari'),
    ('hiking'),('diving'),('wildlife'),('road trip'),
    ('wellness'),('shopping'),('architecture'),('food'),
    ('museums')
ON CONFLICT (name) DO NOTHING;

INSERT INTO destinations (name, country, area) VALUES
    ('Lanzarote', 'Spain', 'Canary Islands'),
    ('Maldives', 'Maldives', 'Indian Ocean'),
    ('Rome', 'Italy', 'Lazio'),
    ('Dresden', 'Germany', 'Saxony'),
    ('Opatija', 'Croatia', 'Kvarner'),
    ('Lisbon', 'Portugal', 'West'),
    ('Madeira', 'Portugal', 'West'),
    ('TromsÃ¸', 'Norway', 'North'),
    ('Santorini', 'Greece', 'South'),
    ('Dolomites', 'Italy', 'Central'),
    ('Marrakech', 'Morocco', 'South'),
    ('Cape Town', 'South Africa', 'South'),
    ('Queenstown', 'New Zealand', 'South'),
    ('Banff', 'Canada', 'North'),
    ('Costa Rica', 'Costa Rica', 'Central'),
    ('Maldives', 'Maldives', 'South'),
    ('Paris', 'France', 'West'),
    ('Amsterdam', 'Netherlands', 'West'),
    ('Dubai', 'United Arab Emirates', 'East'),
    ('Phuket', 'Thailand', 'South'),
    ('Rome', 'Italy', 'South'),
    ('Florence', 'Italy', 'Central'),
    ('Venice', 'Italy', 'North'),
    ('Amalfi Coast', 'Italy', 'South'),
    ('Sicily', 'Italy', 'South'),
    ('Athens', 'Greece', 'South'),
    ('Crete', 'Greece', 'South'),
    ('Istanbul', 'Turkey', 'East'),
    ('Cappadocia', 'Turkey', 'Central'),
    ('London', 'United Kingdom', 'West'),
    ('Edinburgh', 'United Kingdom', 'North'),
    ('Dublin', 'Ireland', 'West'),
    ('Prague', 'Czech Republic', 'Central'),
    ('Vienna', 'Austria', 'Central'),
    ('Budapest', 'Hungary', 'Central'),
    ('Berlin', 'Germany', 'Central'),
    ('Munich', 'Germany', 'Central'),
    ('Copenhagen', 'Denmark', 'North'),
    ('Stockholm', 'Sweden', 'North'),
    ('Lofoten Islands', 'Norway', 'North'),
    ('Helsinki', 'Finland', 'North'),
    ('Tallinn', 'Estonia', 'North'),
    ('Riga', 'Latvia', 'North'),
    ('Warsaw', 'Poland', 'Central'),
    ('Krakow', 'Poland', 'Central'),
    ('Dubrovnik', 'Croatia', 'South'),
    ('Split', 'Croatia', 'South'),
    ('Ljubljana', 'Slovenia', 'Central'),
    ('Lake Bled', 'Slovenia', 'Central'),
    ('Interlaken', 'Switzerland', 'Central'),
    ('Zermatt', 'Switzerland', 'Central'),
    ('Nice', 'France', 'South'),
    ('Provence', 'France', 'South'),
    ('Bordeaux', 'France', 'West'),
    ('Madrid', 'Spain', 'South'),
    ('Seville', 'Spain', 'South'),
    ('Granada', 'Spain', 'South'),
    ('Mallorca', 'Spain', 'South'),
    ('Azores', 'Portugal', 'West'),
    ('Porto', 'Portugal', 'West'),
    ('New York City', 'United States', 'West'),
    ('San Francisco', 'United States', 'West'),
    ('Los Angeles', 'United States', 'West'),
    ('Miami', 'United States', 'South'),
    ('Hawaii', 'United States', 'West'),
    ('Yellowstone', 'United States', 'North'),
    ('Grand Canyon', 'United States', 'West'),
    ('Vancouver', 'Canada', 'West'),
    ('Montreal', 'Canada', 'East'),
    ('Quebec City', 'Canada', 'East'),
    ('Mexico City', 'Mexico', 'Central'),
    ('Cancun', 'Mexico', 'South'),
    ('Oaxaca', 'Mexico', 'South'),
    ('Tulum', 'Mexico', 'South'),
    ('Rio de Janeiro', 'Brazil', 'South'),
    ('Buenos Aires', 'Argentina', 'South'),
    ('Patagonia', 'Argentina', 'South'),
    ('Machu Picchu', 'Peru', 'West'),
    ('Lima', 'Peru', 'West'),
    ('Cartagena', 'Colombia', 'North'),
    ('Galapagos Islands', 'Ecuador', 'West'),
    ('Santiago', 'Chile', 'South'),
    ('Atacama Desert', 'Chile', 'North'),
    ('Tokyo', 'Japan', 'East'),
    ('Osaka', 'Japan', 'West'),
    ('Seoul', 'South Korea', 'East'),
    ('Singapore', 'Singapore', 'South'),
    ('Hong Kong', 'China', 'East'),
    ('Taipei', 'Taiwan', 'East'),
    ('Hanoi', 'Vietnam', 'South'),
    ('Hoi An', 'Vietnam', 'South'),
    ('Bangkok', 'Thailand', 'South'),
    ('Chiang Mai', 'Thailand', 'North'),
    ('Siem Reap', 'Cambodia', 'South'),
    ('Kuala Lumpur', 'Malaysia', 'South'),
    ('Langkawi', 'Malaysia', 'South'),
    ('Boracay', 'Philippines', 'South'),
    ('Palawan', 'Philippines', 'South'),
    ('Goa', 'India', 'South'),
    ('Jaipur', 'India', 'North'),
    ('Chamonix', 'France', 'Alps'),
    ('Reykjavik', 'Iceland', 'Capital Region'),
    ('Kyoto', 'Japan', 'Kansai'),
    ('Cape Town', 'South Africa', 'Western Cape'),
    ('Prague',    'Czechia',   'Bohemia'),
    ('Thessaloniki', 'Greece', 'Macedonia'),
    ('Zagreb', 'Croatia', 'Central Croatia'),
    ('Moscow', 'Russia', 'Central Russia'),
    ('Saint Petersburg', 'Russia', 'Northwest Russia')
ON CONFLICT (name) DO NOTHING;

-- Helper: link destination + activity by names (avoids hard-coded IDs)
INSERT INTO destination_activities
    (destination_id, activity_type_id, start_month, end_month, price_level, quiet_level, luxury_level)
SELECT d.id, a.id, s.start_month, s.end_month, s.price_level, s.quiet_level, s.luxury_level
FROM (VALUES
    -- destination, activity, start, end, price, quiet, luxury
    ('Lanzarote', 'beach', 4, 10, 2, 2, 2),
    ('Rome', 'city_break', 3, 11, 2, 1, 2),
    ('Opatija', 'wellness', 1, 12, 2, 2, 3),
    ('Lanzarote', 'hiking', 3, 11, 1, 3, 1),
    ('Rome', 'cultural', 1, 12, 2, 1, 2),
    ('Chamonix', 'skiing', 12, 4, 3, 2, 3),
    ('Maldives', 'beach', 1, 12, 3, 3, 3),
    ('Dresden', 'city_break', 4, 10, 1, 2, 1),
    ('Chamonix', 'hiking', 6, 9, 2, 2, 2),
    ('Maldives', 'diving', 11, 4, 3, 3, 3),
    ('Dresden', 'cultural', 1, 12, 1, 2, 1),
    ('Reykjavik', 'hiking', 6, 9, 3, 3, 2),
    ('Maldives', 'wellness', 1, 12, 3, 3, 3),
    ('Opatija', 'beach', 5, 9, 1, 2, 2),
    ('Reykjavik', 'cultural', 1, 12, 3, 2, 2),
    ('Kyoto', 'cultural', 1, 12, 2, 2, 3),
    ('Kyoto', 'city_break', 3, 11, 2, 2, 3),
    ('Cape Town', 'safari', 5, 9, 2, 2, 3),
    ('Cape Town', 'beach', 11, 3, 2, 2, 2),
    ('Prague', 'city_break', 4, 10, 1, 1, 2),
    ('Prague', 'cultural', 1, 12, 1, 1, 2),
    ('Lisbon', 'safari', 1, 12, 2, 2, 2),
    ('Lisbon', 'diving', 5, 10, 2, 1, 2),
    ('Lisbon', 'architecture', 3, 11, 2, 2, 2),
    ('Madeira', 'wellness', 3, 11, 2, 3, 2),
    ('Madeira', 'road trip', 4, 10, 2, 3, 2),
    ('Madeira', 'wellness', 1, 12, 2, 3, 2),
    ('Tromsø', 'cultural', 10, 3, 3, 3, 2),
    ('Tromsø', 'wildlife', 11, 3, 3, 3, 2),
    ('Tromsø', 'road trip', 6, 8, 3, 3, 2),
    ('Santorini', 'city_break', 5, 9, 3, 2, 3),
    ('Santorini', 'safari', 4, 10, 3, 2, 3),
    ('Santorini', 'wellness', 5, 10, 3, 3, 3),
    ('Dolomites', 'wellness', 6, 9, 2, 3, 2),
    ('Dolomites', 'skiing', 12, 3, 3, 3, 3),
    ('Dolomites', 'road trip', 5, 10, 2, 3, 2),
    ('Marrakech', 'safari', 1, 12, 2, 1, 2),
    ('Marrakech', 'shopping', 1, 12, 2, 1, 2),
    ('Marrakech', 'architecture', 10, 4, 2, 2, 2),
    ('Cape Town', 'city_break', 11, 3, 2, 2, 2),
    ('Cape Town', 'wellness', 10, 4, 2, 2, 2),
    ('Cape Town', 'wildlife', 6, 10, 3, 3, 2),
    ('Queenstown', 'skiing', 6, 9, 3, 3, 3),
    ('Queenstown', 'wellness', 11, 4, 2, 3, 2),
    ('Queenstown', 'road trip', 10, 4, 2, 3, 2),
    ('Banff', 'skiing', 12, 4, 3, 3, 3),
    ('Banff', 'wellness', 6, 9, 2, 3, 2),
    ('Banff', 'wildlife', 5, 9, 2, 3, 2),
    ('Costa Rica', 'beach', 12, 4, 2, 2, 2),
    ('Costa Rica', 'wellness', 12, 4, 2, 3, 2),
    ('Costa Rica', 'wildlife', 12, 4, 2, 3, 2),
    ('Maldives', 'city_break', 12, 4, 3, 3, 3),
    ('Maldives', 'diving', 12, 4, 3, 3, 3),
    ('Maldives', 'wellness', 1, 12, 3, 3, 3),
    ('Paris', 'hiking', 1, 12, 2, 1, 3),
    ('Paris', 'safari', 1, 12, 3, 1, 3),
    ('Paris', 'architecture', 3, 11, 2, 1, 3),
    ('Amsterdam', 'hiking', 1, 12, 2, 1, 2),
    ('Amsterdam', 'diving', 4, 10, 2, 1, 2),
    ('Amsterdam', 'architecture', 3, 10, 2, 1, 2),
    ('Dubai', 'shopping', 1, 12, 3, 1, 3),
    ('Dubai', 'city_break', 11, 3, 3, 1, 3),
    ('Dubai', 'architecture', 11, 4, 3, 1, 3),
    ('Phuket', 'city_break', 11, 4, 2, 2, 2),
    ('Phuket', 'diving', 11, 4, 2, 2, 2),
    ('Phuket', 'diving', 11, 4, 2, 1, 2),
    ('Rome', 'hiking', 1, 12, 2, 1, 2),
    ('Rome', 'safari', 1, 12, 2, 1, 2),
    ('Rome', 'architecture', 3, 11, 2, 1, 2),
    ('Florence', 'hiking', 1, 12, 2, 2, 2),
    ('Florence', 'safari', 1, 12, 2, 2, 2),
    ('Florence', 'architecture', 3, 11, 2, 2, 2),
    ('Venice', 'hiking', 3, 11, 3, 2, 3),
    ('Venice', 'safari', 3, 11, 3, 2, 3),
    ('Venice', 'architecture', 3, 11, 3, 2, 3),
    ('Amalfi Coast', 'city_break', 5, 9, 3, 2, 3),
    ('Amalfi Coast', 'road trip', 4, 10, 3, 2, 3),
    ('Amalfi Coast', 'safari', 4, 10, 3, 2, 3),
    ('Sicily', 'city_break', 5, 10, 2, 2, 2),
    ('Sicily', 'safari', 1, 12, 2, 2, 2),
    ('Sicily', 'road trip', 4, 10, 2, 2, 2),
    ('Athens', 'hiking', 1, 12, 2, 1, 2),
    ('Athens', 'safari', 1, 12, 2, 1, 2),
    ('Athens', 'architecture', 3, 11, 2, 1, 2),
    ('Crete', 'city_break', 5, 10, 2, 2, 2),
    ('Crete', 'wellness', 4, 10, 2, 3, 2),
    ('Crete', 'safari', 4, 10, 2, 2, 2),
    ('Istanbul', 'safari', 1, 12, 2, 1, 2),
    ('Istanbul', 'shopping', 1, 12, 2, 1, 2),
    ('Istanbul', 'architecture', 3, 11, 2, 1, 2),
    ('Cappadocia', 'wellness', 4, 10, 2, 3, 2),
    ('Cappadocia', 'road trip', 4, 10, 2, 3, 2),
    ('Cappadocia', 'wellness', 1, 12, 2, 3, 2),
    ('London', 'hiking', 1, 12, 2, 1, 3),
    ('London', 'safari', 1, 12, 3, 1, 3),
    ('London', 'shopping', 1, 12, 3, 1, 3),
    ('Edinburgh', 'hiking', 1, 12, 2, 2, 2),
    ('Edinburgh', 'safari', 1, 12, 2, 2, 2),
    ('Edinburgh', 'architecture', 4, 10, 2, 2, 2),
    ('Dublin', 'safari', 1, 12, 2, 1, 2),
    ('Dublin', 'diving', 4, 10, 2, 1, 2),
    ('Dublin', 'hiking', 1, 12, 2, 1, 2),
    ('Prague', 'hiking', 1, 12, 2, 1, 2),
    ('Prague', 'safari', 1, 12, 2, 1, 2),
    ('Prague', 'architecture', 3, 11, 2, 1, 2),
    ('Vienna', 'hiking', 1, 12, 2, 1, 3),
    ('Vienna', 'safari', 1, 12, 3, 1, 3),
    ('Vienna', 'architecture', 3, 11, 2, 1, 3),
    ('Budapest', 'hiking', 1, 12, 2, 1, 2),
    ('Budapest', 'safari', 1, 12, 2, 1, 2),
    ('Budapest', 'wellness', 1, 12, 2, 2, 2),
    ('Berlin', 'hiking', 1, 12, 2, 1, 2),
    ('Berlin', 'diving', 4, 10, 2, 1, 2),
    ('Berlin', 'safari', 1, 12, 2, 1, 2),
    ('Munich', 'safari', 1, 12, 2, 2, 2),
    ('Munich', 'hiking', 1, 12, 2, 2, 2),
    ('Munich', 'shopping', 1, 12, 2, 2, 2),
    ('Copenhagen', 'safari', 1, 12, 3, 2, 3),
    ('Copenhagen', 'architecture', 4, 10, 3, 2, 3),
    ('Copenhagen', 'shopping', 1, 12, 3, 2, 3),
    ('Stockholm', 'hiking', 1, 12, 3, 2, 3),
    ('Stockholm', 'safari', 1, 12, 3, 2, 3),
    ('Stockholm', 'architecture', 4, 10, 3, 2, 3),
    ('Lofoten Islands', 'cultural', 10, 3, 3, 3, 2),
    ('Lofoten Islands', 'wellness', 6, 9, 2, 3, 2),
    ('Lofoten Islands', 'road trip', 5, 9, 3, 3, 2),
    ('Helsinki', 'hiking', 1, 12, 2, 2, 2),
    ('Helsinki', 'wellness', 1, 12, 2, 3, 2),
    ('Helsinki', 'architecture', 4, 10, 2, 2, 2),
    ('Tallinn', 'hiking', 1, 12, 2, 2, 2),
    ('Tallinn', 'safari', 1, 12, 2, 2, 2),
    ('Tallinn', 'architecture', 4, 10, 2, 2, 2),
    ('Riga', 'hiking', 1, 12, 2, 2, 2),
    ('Riga', 'safari', 1, 12, 2, 2, 2),
    ('Riga', 'architecture', 4, 10, 2, 2, 2),
    ('Warsaw', 'hiking', 1, 12, 2, 1, 2),
    ('Warsaw', 'safari', 1, 12, 2, 1, 2),
    ('Warsaw', 'architecture', 4, 10, 2, 1, 2),
    ('Krakow', 'hiking', 1, 12, 2, 2, 2),
    ('Krakow', 'safari', 1, 12, 2, 2, 2),
    ('Krakow', 'architecture', 4, 10, 2, 2, 2),
    ('Dubrovnik', 'city_break', 5, 9, 3, 2, 3),
    ('Dubrovnik', 'safari', 4, 10, 3, 2, 3),
    ('Dubrovnik', 'architecture', 4, 10, 3, 2, 3),
    ('Split', 'city_break', 5, 9, 2, 2, 2),
    ('Split', 'diving', 5, 9, 2, 1, 2),
    ('Split', 'safari', 4, 10, 2, 2, 2),
    ('Ljubljana', 'wellness', 4, 10, 2, 3, 2),
    ('Ljubljana', 'safari', 1, 12, 2, 2, 2),
    ('Ljubljana', 'architecture', 4, 10, 2, 3, 2),
    ('Lake Bled', 'wellness', 5, 9, 2, 3, 2),
    ('Lake Bled', 'wellness', 1, 12, 2, 3, 2),
    ('Lake Bled', 'road trip', 5, 9, 2, 3, 2),
    ('Interlaken', 'wellness', 6, 9, 3, 3, 3),
    ('Interlaken', 'skiing', 12, 3, 3, 3, 3),
    ('Interlaken', 'road trip', 5, 9, 3, 3, 3),
    ('Zermatt', 'skiing', 12, 4, 3, 3, 3),
    ('Zermatt', 'wellness', 6, 9, 3, 3, 3),
    ('Zermatt', 'wellness', 1, 12, 3, 3, 3),
    ('Nice', 'city_break', 5, 9, 3, 2, 3),
    ('Nice', 'safari', 4, 10, 3, 2, 3),
    ('Nice', 'wellness', 1, 12, 3, 2, 3),
    ('Provence', 'safari', 4, 10, 3, 3, 3),
    ('Provence', 'road trip', 4, 10, 3, 3, 3),
    ('Provence', 'wellness', 1, 12, 3, 3, 3),
    ('Bordeaux', 'safari', 1, 12, 3, 2, 3),
    ('Bordeaux', 'road trip', 4, 10, 3, 2, 3),
    ('Bordeaux', 'wellness', 1, 12, 3, 2, 3),
    ('Madrid', 'hiking', 1, 12, 2, 1, 2),
    ('Madrid', 'safari', 1, 12, 2, 1, 2),
    ('Madrid', 'diving', 4, 10, 2, 1, 2),
    ('Seville', 'safari', 1, 12, 2, 2, 2),
    ('Seville', 'architecture', 3, 11, 2, 2, 2),
    ('Seville', 'diving', 4, 10, 2, 1, 2),
    ('Granada', 'architecture', 3, 11, 2, 2, 2),
    ('Granada', 'safari', 1, 12, 2, 2, 2),
    ('Granada', 'hiking', 1, 12, 2, 2, 2),
    ('Mallorca', 'city_break', 5, 9, 3, 2, 3),
    ('Mallorca', 'diving', 5, 9, 3, 1, 3),
    ('Mallorca', 'wellness', 1, 12, 3, 2, 3),
    ('Azores', 'wellness', 3, 11, 2, 3, 2),
    ('Azores', 'wildlife', 4, 10, 2, 3, 2),
    ('Azores', 'road trip', 4, 10, 2, 3, 2),
    ('Porto', 'safari', 1, 12, 2, 2, 2),
    ('Porto', 'architecture', 3, 11, 2, 2, 2),
    ('Porto', 'city_break', 6, 9, 2, 2, 2),
    ('New York City', 'hiking', 1, 12, 3, 1, 3),
    ('New York City', 'safari', 1, 12, 3, 1, 3),
    ('New York City', 'diving', 1, 12, 3, 1, 3),
    ('San Francisco', 'safari', 1, 12, 3, 1, 3),
    ('San Francisco', 'hiking', 1, 12, 3, 1, 3),
    ('San Francisco', 'architecture', 1, 12, 3, 1, 3),
    ('Los Angeles', 'city_break', 5, 10, 3, 1, 3),
    ('Los Angeles', 'diving', 1, 12, 3, 1, 3),
    ('Los Angeles', 'shopping', 1, 12, 3, 1, 3),
    ('Miami', 'city_break', 11, 4, 3, 1, 3),
    ('Miami', 'diving', 1, 12, 3, 1, 3),
    ('Miami', 'safari', 1, 12, 3, 1, 3),
    ('Hawaii', 'city_break', 1, 12, 3, 2, 3),
    ('Hawaii', 'beach', 11, 4, 3, 2, 3),
    ('Hawaii', 'wellness', 1, 12, 3, 3, 3),
    ('Yellowstone', 'wildlife', 5, 9, 2, 3, 2),
    ('Yellowstone', 'wellness', 5, 9, 2, 3, 2),
    ('Yellowstone', 'road trip', 5, 9, 2, 3, 2),
    ('Grand Canyon', 'wellness', 3, 11, 2, 3, 2),
    ('Grand Canyon', 'road trip', 3, 11, 2, 3, 2),
    ('Grand Canyon', 'wildlife', 3, 11, 2, 3, 2),
    ('Vancouver', 'wellness', 5, 10, 3, 3, 3),
    ('Vancouver', 'safari', 1, 12, 3, 2, 3),
    ('Vancouver', 'wellness', 1, 12, 3, 3, 3),
    ('Montreal', 'hiking', 1, 12, 2, 1, 2),
    ('Montreal', 'safari', 1, 12, 2, 1, 2),
    ('Montreal', 'architecture', 1, 12, 2, 1, 2),
    ('Quebec City', 'hiking', 1, 12, 2, 2, 2),
    ('Quebec City', 'safari', 1, 12, 2, 2, 2),
    ('Quebec City', 'architecture', 1, 12, 2, 2, 2),
    ('Mexico City', 'safari', 1, 12, 2, 1, 2),
    ('Mexico City', 'hiking', 1, 12, 2, 1, 2),
    ('Mexico City', 'architecture', 1, 12, 2, 1, 2),
    ('Cancun', 'city_break', 11, 4, 2, 1, 2),
    ('Cancun', 'diving', 11, 4, 2, 1, 2),
    ('Cancun', 'diving', 11, 4, 2, 2, 2),
    ('Oaxaca', 'safari', 1, 12, 2, 2, 2),
    ('Oaxaca', 'hiking', 1, 12, 2, 2, 2),
    ('Oaxaca', 'wellness', 1, 12, 2, 3, 2),
    ('Tulum', 'city_break', 11, 4, 3, 2, 3),
    ('Tulum', 'wellness', 1, 12, 3, 2, 3),
    ('Tulum', 'diving', 11, 4, 3, 2, 3),
    ('Rio de Janeiro', 'city_break', 11, 3, 2, 1, 2),
    ('Rio de Janeiro', 'diving', 1, 12, 2, 1, 2),
    ('Rio de Janeiro', 'safari', 1, 12, 2, 1, 2),
    ('Buenos Aires', 'safari', 1, 12, 2, 1, 2),
    ('Buenos Aires', 'diving', 1, 12, 2, 1, 2),
    ('Buenos Aires', 'architecture', 1, 12, 2, 1, 2),
    ('Patagonia', 'wellness', 11, 3, 3, 3, 2),
    ('Patagonia', 'road trip', 11, 3, 3, 3, 2),
    ('Patagonia', 'wildlife', 11, 3, 3, 3, 2),
    ('Machu Picchu', 'wellness', 5, 9, 2, 3, 2),
    ('Machu Picchu', 'hiking', 4, 10, 2, 3, 2),
    ('Machu Picchu', 'road trip', 5, 9, 2, 3, 2),
    ('Lima', 'safari', 1, 12, 2, 1, 2),
    ('Lima', 'hiking', 1, 12, 2, 1, 2),
    ('Lima', 'architecture', 1, 12, 2, 1, 2),
    ('Cartagena', 'city_break', 12, 4, 2, 1, 2),
    ('Cartagena', 'safari', 1, 12, 2, 1, 2),
    ('Cartagena', 'architecture', 1, 12, 2, 1, 2),
    ('Galapagos Islands', 'wildlife', 6, 11, 3, 3, 3),
    ('Galapagos Islands', 'diving', 6, 11, 3, 3, 3),
    ('Galapagos Islands', 'road trip', 6, 11, 3, 3, 3),
    ('Santiago', 'safari', 1, 12, 2, 1, 2),
    ('Santiago', 'hiking', 1, 12, 2, 1, 2),
    ('Santiago', 'architecture', 1, 12, 2, 1, 2),
    ('Atacama Desert', 'road trip', 3, 11, 3, 3, 3),
    ('Atacama Desert', 'wellness', 3, 11, 3, 3, 3),
    ('Atacama Desert', 'wellness', 1, 12, 3, 3, 3),
    ('Tokyo', 'safari', 1, 12, 3, 1, 3),
    ('Tokyo', 'hiking', 1, 12, 3, 1, 3),
    ('Tokyo', 'shopping', 1, 12, 3, 1, 3),
    ('Osaka', 'safari', 1, 12, 2, 1, 2),
    ('Osaka', 'diving', 1, 12, 2, 1, 2),
    ('Osaka', 'shopping', 1, 12, 2, 1, 2),
    ('Seoul', 'safari', 1, 12, 2, 1, 2),
    ('Seoul', 'shopping', 1, 12, 2, 1, 2),
    ('Seoul', 'diving', 1, 12, 2, 1, 2),
    ('Singapore', 'safari', 1, 12, 3, 1, 3),
    ('Singapore', 'shopping', 1, 12, 3, 1, 3),
    ('Singapore', 'architecture', 1, 12, 3, 1, 3),
    ('Hong Kong', 'safari', 1, 12, 3, 1, 3),
    ('Hong Kong', 'shopping', 1, 12, 3, 1, 3),
    ('Hong Kong', 'diving', 1, 12, 3, 1, 3),
    ('Taipei', 'safari', 1, 12, 2, 1, 2),
    ('Taipei', 'hiking', 1, 12, 2, 1, 2),
    ('Taipei', 'wellness', 10, 4, 2, 2, 2),
    ('Hanoi', 'safari', 1, 12, 1, 1, 1),
    ('Hanoi', 'hiking', 10, 4, 1, 1, 1),
    ('Hanoi', 'architecture', 10, 4, 1, 1, 1),
    ('Hoi An', 'safari', 1, 12, 1, 2, 1),
    ('Hoi An', 'city_break', 3, 9, 1, 2, 1),
    ('Hoi An', 'architecture', 1, 12, 1, 2, 1),
    ('Bangkok', 'safari', 1, 12, 2, 1, 2),
    ('Bangkok', 'diving', 1, 12, 2, 1, 2),
    ('Bangkok', 'shopping', 1, 12, 2, 1, 2),
    ('Chiang Mai', 'hiking', 11, 2, 1, 3, 1),
    ('Chiang Mai', 'wellness', 11, 2, 1, 3, 1),
    ('Chiang Mai', 'wellness', 1, 12, 1, 3, 1),
    ('Siem Reap', 'hiking', 11, 3, 1, 2, 1),
    ('Siem Reap', 'hiking', 11, 3, 1, 2, 1),
    ('Siem Reap', 'architecture', 11, 3, 1, 2, 1),
    ('Kuala Lumpur', 'safari', 1, 12, 2, 1, 2),
    ('Kuala Lumpur', 'shopping', 1, 12, 2, 1, 2),
    ('Kuala Lumpur', 'architecture', 1, 12, 2, 1, 2),
    ('Langkawi', 'city_break', 11, 4, 2, 2, 2),
    ('Langkawi', 'diving', 11, 4, 2, 2, 2),
    ('Langkawi', 'wellness', 1, 12, 2, 3, 2),
    ('Boracay', 'city_break', 11, 5, 2, 2, 2),
    ('Boracay', 'diving', 11, 5, 2, 2, 2),
    ('Boracay', 'diving', 11, 5, 2, 1, 2),
    ('Palawan', 'city_break', 11, 5, 2, 3, 2),
    ('Palawan', 'diving', 11, 5, 2, 3, 2),
    ('Palawan', 'wildlife', 11, 5, 2, 3, 2),
    ('Goa', 'city_break', 11, 3, 1, 2, 1),
    ('Goa', 'wellness', 1, 12, 1, 2, 1),
    ('Goa', 'diving', 11, 3, 1, 1, 1),
    ('Jaipur', 'hiking', 10, 3, 2, 2, 2),
    ('Jaipur', 'safari', 1, 12, 2, 2, 2),
    ('Jaipur', 'architecture', 10, 3, 2, 2, 2),
    ('Thessaloniki', 'beach', 5, 9, 2, 2, 2),
    ('Thessaloniki', 'cultural', 3, 11, 2, 2, 2),
    ('Thessaloniki', 'city_break', 4, 10, 2, 2, 2),
    ('Thessaloniki', 'food', 1, 12, 2, 2, 2),
    ('Zagreb', 'city_break', 3, 11, 1, 2, 1),
    ('Zagreb', 'cultural', 1, 12, 1, 2, 1),
    ('Zagreb', 'food', 1, 12, 1, 2, 1),
    ('Zagreb', 'museums', 1, 12, 1, 2, 1),
    ('Moscow', 'cultural', 1, 12, 2, 1, 2),
    ('Moscow', 'city_break', 5, 9, 2, 1, 2),
    ('Moscow', 'museums', 1, 12, 2, 1, 2),
    ('Moscow', 'shopping', 1, 12, 3, 1, 3),
    ('Saint Petersburg', 'cultural', 5, 9, 2, 2, 2),
    ('Saint Petersburg', 'city_break', 5, 9, 2, 2, 2),
    ('Saint Petersburg', 'museums',  1, 12, 2, 2, 2),
    ('Saint Petersburg', 'architecture', 5, 9, 2, 2, 2)
) AS s(dest_name, act_name, start_month, end_month, price_level, quiet_level, luxury_level)
JOIN destinations   d ON d.name = s.dest_name
JOIN activity_types a ON a.name = s.act_name
ON CONFLICT (destination_id, activity_type_id) DO NOTHING;
